version: "1"

default:
    description: "Backup all files designated here"
    repository: /backup_repo
    password-file: /cfg/password.txt
    backup:
        source:
            - /Photos
            - /immich
            - /npm
            - /file-upload
        exclude:
            - "**/cache"
            - "**/tmp"
    retention:
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 6