version: "1"

# When adding/debugging, you can do this to show just rendered template (without running the actual backup):
# docker compose run --rm resticprofile --name <profile> --trace show

# this injects this literal block (indents and all) into the locations referenced.
# unfortunately this is a biproduct of how resticprofile parses this.
{{ define "failure_hook" }}
        send-after-fail:
            method: POST
            url: "{{ .Env.HA_WEBHOOK_URL }}"
            body-template: /cfg/failure_template.json
            headers:
                - name: Content-Type
                  value: application/json
{{ end }}

local:
    repository: /backup_repo
    password-file: /cfg/password.txt
    retention:
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 6
    backup:
{{ template "failure_hook" . }}

remote:
    inherit: local
    copy:
        initialize: true
        initialize-copy-chunker-params: true
        repository: "{{ .Env.BACKBLAZE_BUCKET_PATH }}"
        password-file: /cfg/password.txt
{{ template "failure_hook" . }}

immich:
    inherit: local
    backup:
        source:
            - /immich

paperless-ngx:
    inherit: local
    backup:
        source:
            - /paperless-ngx

documents:
    inherit: local
    backup:
        source:
            - /documents
        exclude:
            - /paperless-ngx

home-assistant:
    inherit: local
    backup:
        source:
            - /home-assistant

jellyfin:
    inherit: local
    backup:
        source:
            - /jellyfin

npm:
    inherit: local
    backup:
        source:
            - /npm
        exclude:
            - "**/cache"
            - "**/tmp"

file-upload:
    inherit: local
    backup:
        source:
            - /file-upload
        exclude:
            - "**/cache"
            - "**/tmp"

groups:
    # everything but jellyfin, which is handled separately
    almost_everything:
        - immich
        - paperless-ngx
        - documents
        - home-assistant
        - npm
        - file-upload