name: paperless-ngx

services:
  broker:
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    volumes:
      - ${VALKEY_DATA_PATH}:/data

  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql
    env_file: ${SECRETS_DOTENV}
    environment:
      POSTGRES_DB: ${PAPERLESS_DBNAME:-paperless}
      POSTGRES_USER: ${PAPERLESS_DBUSER:-paperless}

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: "true"

  tika:
    image: apache/tika:latest
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "${WEBSERVER_PORT}:8000"
    volumes:
      - ${PAPERLESS_DATA_PATH}:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_PATH}:/usr/src/paperless/media
      - ${PAPERLESS_EXPORT_PATH}:/usr/src/paperless/export
      - ${PAPERLESS_CONSUME_PATH}:/usr/src/paperless/consume
    env_file: ${SECRETS_DOTENV}
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBUSER: ${PAPERLESS_DBUSER:-paperless}
      PAPERLESS_DBNAME: ${PAPERLESS_DBNAME:-paperless}
      USERMAP_UID: ${USERMAP_UID:-99}
      USERMAP_GID: ${USERMAP_GID:-100}
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_TIKA_ENABLED: "true"
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
